import { computed } from 'vue';

export function useTips() {
  const tipsGlassFirst = computed(() => [
    {
      title: 'SECTIONS.TIPS.GLASS_FIRST.WHY_SMOKE_THE_GLASS.TITLE',
      steps: [
        'SECTIONS.TIPS.GLASS_FIRST.WHY_SMOKE_THE_GLASS.STEPS[0]',
        'SECTIONS.TIPS.GLASS_FIRST.WHY_SMOKE_THE_GLASS.STEPS[1]',
        'SECTIONS.TIPS.GLASS_FIRST.WHY_SMOKE_THE_GLASS.STEPS[2]',
      ],
    },
    {
      title: 'SECTIONS.TIPS.GLASS_FIRST.HOW_TO_SMOKE_THE_GLASS.TITLE',
      steps: [
        'SECTIONS.TIPS.GLASS_FIRST.HOW_TO_SMOKE_THE_GLASS.STEPS[0]',
        'SECTIONS.TIPS.GLASS_FIRST.HOW_TO_SMOKE_THE_GLASS.STEPS[1]',
        'SECTIONS.TIPS.GLASS_FIRST.HOW_TO_SMOKE_THE_GLASS.STEPS[2]',
        'SECTIONS.TIPS.GLASS_FIRST.HOW_TO_SMOKE_THE_GLASS.STEPS[3]',
        'SECTIONS.TIPS.GLASS_FIRST.HOW_TO_SMOKE_THE_GLASS.STEPS[4]',
        'SECTIONS.TIPS.GLASS_FIRST.HOW_TO_SMOKE_THE_GLASS.STEPS[5]',
      ],
    },
  ]);

  const tipsWhiskeyFirst = computed(() => [
    {
      title: 'SECTIONS.TIPS.WHISKEY_FIRST.WHY_SMOKE_THE_GLASS.TITLE',
      steps: [
        'SECTIONS.TIPS.WHISKEY_FIRST.WHY_SMOKE_THE_GLASS.STEPS[0]',
        'SECTIONS.TIPS.WHISKEY_FIRST.WHY_SMOKE_THE_GLASS.STEPS[1]',
        'SECTIONS.TIPS.WHISKEY_FIRST.WHY_SMOKE_THE_GLASS.STEPS[2]',
      ],
    },
    {
      title: 'SECTIONS.TIPS.WHISKEY_FIRST.HOW_TO_SMOKE_THE_GLASS.TITLE',
      steps: [
        'SECTIONS.TIPS.WHISKEY_FIRST.HOW_TO_SMOKE_THE_GLASS.STEPS[0]',
        'SECTIONS.TIPS.WHISKEY_FIRST.HOW_TO_SMOKE_THE_GLASS.STEPS[1]',
        'SECTIONS.TIPS.WHISKEY_FIRST.HOW_TO_SMOKE_THE_GLASS.STEPS[2]',
        'SECTIONS.TIPS.WHISKEY_FIRST.HOW_TO_SMOKE_THE_GLASS.STEPS[3]',
        'SECTIONS.TIPS.WHISKEY_FIRST.HOW_TO_SMOKE_THE_GLASS.STEPS[4]',
        'SECTIONS.TIPS.WHISKEY_FIRST.HOW_TO_SMOKE_THE_GLASS.STEPS[5]',
        'SECTIONS.TIPS.WHISKEY_FIRST.HOW_TO_SMOKE_THE_GLASS.STEPS[6]',
      ],
    },
  ]);

  const tipsConclusions = computed(() => {
    return {
      title: 'SECTIONS.TIPS.CONCLUSIONS.TITLE',
      description: 'SECTIONS.TIPS.CONCLUSIONS.DESCRIPTION',
      steps: [
        'SECTIONS.TIPS.CONCLUSIONS.STEPS[0]',
        'SECTIONS.TIPS.CONCLUSIONS.STEPS[1]',
      ],
    };
  });

  return {
    tipsGlassFirst,
    tipsWhiskeyFirst,
    tipsConclusions,
  };
}
