import { computed } from 'vue';

export function useInstructions() {
  const instructions = computed(() => [
    'SECTIONS.INSTRUCTIONS.LIST.SMOKER_SETUP',
    'SECTIONS.INSTRUCTIONS.LIST.WOOD_CHIPS',
    'SECTIONS.INSTRUCTIONS.LIST.TORCH',
    'SECTIONS.INSTRUCTIONS.LIST.SMOKE_TIME',
    'SECTIONS.INSTRUCTIONS.LIST.HANDLING_SAFETY',
    'SECTIONS.INSTRUCTIONS.LIST.POUR_WHISKEY',
    'SECTIONS.INSTRUCTIONS.LIST.METAL_ICE_CUBES',
    'SECTIONS.INSTRUCTIONS.LIST.SERVING',
  ]);

  const additionalTips = computed(() => [
    'SECTIONS.INSTRUCTIONS.TIPS[0]',
    'SECTIONS.INSTRUCTIONS.TIPS[1]',
    'SECTIONS.INSTRUCTIONS.TIPS[2]',
  ]);

  const torchInstructions = computed(() => [
    'SECTIONS.INSTRUCTIONS.TORCH.STEPS[0]',
    'SECTIONS.INSTRUCTIONS.TORCH.STEPS[1]',
    'SECTIONS.INSTRUCTIONS.TORCH.STEPS[2]',
    'SECTIONS.INSTRUCTIONS.TORCH.STEPS[3]',
    'SECTIONS.INSTRUCTIONS.TORCH.STEPS[4]',
  ]);

  const stonesInstructions = computed(() => [
    'SECTIONS.INSTRUCTIONS.STONES.STEPS[0]',
    'SECTIONS.INSTRUCTIONS.STONES.STEPS[1]',
    'SECTIONS.INSTRUCTIONS.STONES.STEPS[2]',
    'SECTIONS.INSTRUCTIONS.STONES.STEPS[3]',
    'SECTIONS.INSTRUCTIONS.STONES.STEPS[4]',
    'SECTIONS.INSTRUCTIONS.STONES.STEPS[5]',
    'SECTIONS.INSTRUCTIONS.STONES.STEPS[6]',
  ]);

  const metalVsIceAdvantages = computed(() => [
    {
      title: 'SECTIONS.INSTRUCTIONS.ADVANTAGES.NON_DILUTING.TITLE',
      steps: [
        'SECTIONS.INSTRUCTIONS.ADVANTAGES.NON_DILUTING.STEPS[0]',
        'SECTIONS.INSTRUCTIONS.ADVANTAGES.NON_DILUTING.STEPS[1]',
      ],
    },
    {
      title: 'SECTIONS.INSTRUCTIONS.ADVANTAGES.LONG_LASTING_COOLING.TITLE',
      steps: [
        'SECTIONS.INSTRUCTIONS.ADVANTAGES.LONG_LASTING_COOLING.STEPS[0]',
        'SECTIONS.INSTRUCTIONS.ADVANTAGES.LONG_LASTING_COOLING.STEPS[1]',
      ],
    },
    {
      title: 'SECTIONS.INSTRUCTIONS.ADVANTAGES.MATERIAL_AND_SAFETY.TITLE',
      steps: [
        'SECTIONS.INSTRUCTIONS.ADVANTAGES.MATERIAL_AND_SAFETY.STEPS[0]',
        'SECTIONS.INSTRUCTIONS.ADVANTAGES.MATERIAL_AND_SAFETY.STEPS[1]',
      ],
    },
    {
      title: 'SECTIONS.INSTRUCTIONS.ADVANTAGES.REUSABLE.TITLE',
      steps: [
        'SECTIONS.INSTRUCTIONS.ADVANTAGES.REUSABLE.STEPS[0]',
        'SECTIONS.INSTRUCTIONS.ADVANTAGES.REUSABLE.STEPS[1]',
      ],
    },
    {
      title: 'SECTIONS.INSTRUCTIONS.ADVANTAGES.AESTHETIC_APPEAL.TITLE',
      steps: [
        'SECTIONS.INSTRUCTIONS.ADVANTAGES.AESTHETIC_APPEAL.STEPS[0]',
        'SECTIONS.INSTRUCTIONS.ADVANTAGES.AESTHETIC_APPEAL.STEPS[1]',
      ],
    },
    {
      title:
        'SECTIONS.INSTRUCTIONS.ADVANTAGES.ENHANCED_COOLING_EFFICIENCY.TITLE',
      steps: [
        'SECTIONS.INSTRUCTIONS.ADVANTAGES.ENHANCED_COOLING_EFFICIENCY.STEPS[0]',
        'SECTIONS.INSTRUCTIONS.ADVANTAGES.ENHANCED_COOLING_EFFICIENCY.STEPS[1]',
      ],
    },
  ]);

  const cleaningMaintenanceStones = computed(() => [
    'SECTIONS.INSTRUCTIONS.STONES.CLEANING.STEPS[0]',
    'SECTIONS.INSTRUCTIONS.STONES.CLEANING.STEPS[1]',
    'SECTIONS.INSTRUCTIONS.STONES.CLEANING.STEPS[2]',
    'SECTIONS.INSTRUCTIONS.STONES.CLEANING.STEPS[3]',
  ]);

  return {
    instructions,
    additionalTips,
    torchInstructions,
    stonesInstructions,
    metalVsIceAdvantages,
    cleaningMaintenanceStones,
  };
}
